version: "3.9"

services:
  database_boost:
    image: postgres
    container_name: database_boost
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=boost
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: boost
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_boost
    depends_on:
      - database_boost



volumes:
  pgdata:
    driver: local
